### ISSUE TITLE
希望加入自定义背景图片

### ISSUE THREAD

**Issue by mjdgcn** [zooPanda/Learning-together#1]
能加入自定义背景图片就更完美了， 做成透明背景。

**Comment by zooPanda** [comment]
> 能加入自定义背景图片就更完美了， 做成透明背景。

还在学习中，慢慢加吧。

**Comment by mojito8327** [comment]
怎么改背景颜色呢？

**Comment by zooPanda** [comment]
> 怎么改背景颜色呢？
> 
> 

程序内运行可以设置

**Comment by mojito8327** [comment]
我不太懂程序 没看到背景颜色的代码，还望指导下，谢谢

**Comment by zooPanda** [comment]
> 我不太懂程序 没看到背景颜色的代码，还望指导下，谢谢

你添加的是第几版的代码呢？

**Comment by mojito8327** [comment]
第一版的

**Comment by zooPanda** [comment]
> 第一版的
> 
> 

第一版的不支持修改颜色
第二版的支持修改文字及背景颜色。

**Comment by mojito8327** [comment]
好的 谢谢

**Comment by mojito8327** [comment]
哦，看到了 谢谢
